// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ssd_task.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20240827183919_initialcomment")]
    partial class initialcomment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ssd_task.Models.Employee", b =>
                {
                    b.Property<string>("Personnel_Records")
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Address_2")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EMail_Home")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Forenames")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("varchar(450)");

                    b.HasKey("Personnel_Records");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
